# Application Config
baseUrl=https://www.saucedemo.com
browser=chrome
implicitWait=10
explicitWait=15

# Credentials
username=standard_user
password=secret_sauce

# Report Config
reportPath=reports/ExtentReport.html
screenshotPath=screenshots/
logPath=logs/app.log
